python prepare_run.py --channel="eeem" --year="2016" --sample="mc"
python prepare_run.py --channel="eeet" --year="2016" --sample="mc"
python prepare_run.py --channel="eemt" --year="2016" --sample="mc"
python prepare_run.py --channel="eett" --year="2016" --sample="mc"
python prepare_run.py --channel="mmem" --year="2016" --sample="mc"
python prepare_run.py --channel="mmet" --year="2016" --sample="mc"
python prepare_run.py --channel="mmmt" --year="2016" --sample="mc"
python prepare_run.py --channel="mmtt" --year="2016" --sample="mc"

python prepare_run.py --channel="eeem" --year="2016" --sample="data"
python prepare_run.py --channel="eeet" --year="2016" --sample="data"
python prepare_run.py --channel="eemt" --year="2016" --sample="data"
python prepare_run.py --channel="eett" --year="2016" --sample="data"
python prepare_run.py --channel="mmem" --year="2016" --sample="data"
python prepare_run.py --channel="mmet" --year="2016" --sample="data"
python prepare_run.py --channel="mmmt" --year="2016" --sample="data"
python prepare_run.py --channel="mmtt" --year="2016" --sample="data"

python prepare_run.py --channel="eeem" --year="2017" --sample="mc"
python prepare_run.py --channel="eeet" --year="2017" --sample="mc"
python prepare_run.py --channel="eemt" --year="2017" --sample="mc"
python prepare_run.py --channel="eett" --year="2017" --sample="mc"
python prepare_run.py --channel="mmem" --year="2017" --sample="mc"
python prepare_run.py --channel="mmet" --year="2017" --sample="mc"
python prepare_run.py --channel="mmmt" --year="2017" --sample="mc"
python prepare_run.py --channel="mmtt" --year="2017" --sample="mc"

python prepare_run.py --channel="eeem" --year="2017" --sample="data"
python prepare_run.py --channel="eeet" --year="2017" --sample="data"
python prepare_run.py --channel="eemt" --year="2017" --sample="data"
python prepare_run.py --channel="eett" --year="2017" --sample="data"
python prepare_run.py --channel="mmem" --year="2017" --sample="data"
python prepare_run.py --channel="mmet" --year="2017" --sample="data"
python prepare_run.py --channel="mmmt" --year="2017" --sample="data"
python prepare_run.py --channel="mmtt" --year="2017" --sample="data"

python prepare_run.py --channel="eeem" --year="2018" --sample="mc"
python prepare_run.py --channel="eeet" --year="2018" --sample="mc"
python prepare_run.py --channel="eemt" --year="2018" --sample="mc"
python prepare_run.py --channel="eett" --year="2018" --sample="mc"
python prepare_run.py --channel="mmem" --year="2018" --sample="mc"
python prepare_run.py --channel="mmet" --year="2018" --sample="mc"
python prepare_run.py --channel="mmmt" --year="2018" --sample="mc"
python prepare_run.py --channel="mmtt" --year="2018" --sample="mc"

python prepare_run.py --channel="eeem" --year="2018" --sample="data" 
python prepare_run.py --channel="eeet" --year="2018" --sample="data"
python prepare_run.py --channel="eemt" --year="2018" --sample="data"
python prepare_run.py --channel="eett" --year="2018" --sample="data"
python prepare_run.py --channel="mmem" --year="2018" --sample="data"
python prepare_run.py --channel="mmet" --year="2018" --sample="data"
python prepare_run.py --channel="mmmt" --year="2018" --sample="data"
python prepare_run.py --channel="mmtt" --year="2018" --sample="data"

